In [84]:
import tensorflow as tf
from tensorflow.keras import backend as K
import numpy as np
from numpy import zeros, newaxis
import tensorboard


model = tf.keras.models.Sequential([
  tf.keras.layers.Conv2D(1,3,(1,1),'SAME', activation=None,use_bias=False,input_shape=(4,4,1)),
  tf.keras.layers.ReLU(),
  tf.keras.layers.MaxPool2D(strides =2),
  tf.keras.layers.Flatten(),
  tf.keras.layers.Dense(2,activation='sigmoid',use_bias=False),
  tf.keras.layers.Dense(2, activation='sigmoid',use_bias=False),
  tf.keras.layers.Softmax()
])
# weight init
weights0 = np.array([[0.,-1.,0.],[ -1.,4.,-1.],[ 0.,-1.,0.]]) # CNN
weights0 = weights0[...,newaxis]
weights0 = weights0[...,newaxis]
model.layers[0].set_weights([weights0])
weights1 = np.array([[0.1,0.05],[ -0.05,-0.02,],[ 0.05, 0.03,],[ -0.02,-0.07]]) #D1
model.layers[4].set_weights([weights1])
weights2 = np.array([[-0.4,0.5],[-1,-0.5]])#D2
model.layers[5].set_weights([weights2])
# input 
input = np.array([[10,10,10,10],[10,30,10,30],[10,10,10,10],[10,10,10,20]])
input = np.expand_dims(input, axis=0)



for layerIndex, layer in enumerate(model.layers):
    func = K.function([model.get_layer(index=0).input], layer.output)
    layerOutput = func([input]) 
    print(layerOutput)



[[[[ 20.]
   [-10.]
   [ 10.]
   [  0.]]

  [[-10.]
   [ 80.]
   [-40.]
   [ 90.]]

  [[ 10.]
   [-20.]
   [  0.]
   [-20.]]

  [[ 20.]
   [ 10.]
   [  0.]
   [ 60.]]]]
[[[[20.]
   [ 0.]
   [10.]
   [ 0.]]

  [[ 0.]
   [80.]
   [ 0.]
   [90.]]

  [[10.]
   [ 0.]
   [ 0.]
   [ 0.]]

  [[20.]
   [10.]
   [ 0.]
   [60.]]]]
[[[[80.]
   [90.]]

  [[20.]
   [60.]]]]
[[80. 90. 20. 60.]]
[[0.96442884 0.1978161 ]]
[[0.3581075 0.5946703]]
[[0.4411336  0.55886644]]
